name = "threads-garden"
account_id = "81c1ee2e102b2279be9311f73c01ec7f"
workers_dev = true

routes = [
	{ pattern = "threads.garden", custom_domain = true, zone_name =  "threads.garden" }
]

usage_model = 'bundled'
compatibility_flags = []

compatibility_date = "2022-01-31"

kv_namespaces = [ ]

main = "out/index.mjs"


[build]
command = "npm run build"
watch_dir = "./src"

[durable_objects]
bindings = [
  {name = "USER", class_name = "UserDO"},
  {name = "THREAD", class_name = "ThreadDO"}
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["UserDO"]

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["ThreadDO"]

[[rules]]
type = "ESModule"
globs = ["**/*.mjs"]


